services:
  besu:
    container_name: besu
    image: hyperledger/besu:latest
    pull_policy: always
    command:
      - --logging=ALL
      - --discovery-enabled
      - --bootnodes=enode://663ce222c6ca01f14303c290966a21d387cc1fa77e3eec3c6b6c394740f4c56429fd5645b0fb25c75dc4260b0bca3167943566a261b05adcbdaf82012daa56d1@49.13.137.162:30303,enode://f632e549c9c44980f43f99a9218dda01cd6771379c154dec9dc84e9d039c9124294fab63ab45a2232ba23b1bbbb56a9ea913d98a212579ff114e80f36ab7e8f5@95.31.7.226:30303,enode://48364dd43309b862aae98e0ceac0da35b92cd8c04f082054dce68be1736d99bd72adc4489ae2b231d9e64243ad353d4ec3c7820e3037ba7f4436ae428d3810d4@217.76.63.73:30303
      - --host-allowlist=*
      - --rpc-http-enabled
      - --rpc-http-api=ETH,NET,WEB3,TXPOOL,TRACE,DEBUG,ADMIN
      - --rpc-http-host=127.0.0.1
      - --engine-rpc-enabled
      - --engine-jwt-disabled
      - --engine-host-allowlist=127.0.0.1
      - --genesis-file=/etc/besu/genesis.json
      - --data-path=/var/lib/besu
    volumes:
      - ./besu:/var/lib/besu
      - ./log/besu:/opt/besu/logs
      - ./genesis.json:/etc/besu/genesis.json:ro
      - ./log4j.xml:/etc/besu/log4j2.xml:ro
    environment:
      - LOG4J_CONFIGURATION_FILE=/etc/besu/log4j2.xml
    healthcheck:
      test: ["CMD-SHELL", "echo", "GET / HTTP/1.0\r\n", ">", "/dev/tcp/127.0.0.1/8545"]
      interval: 10s
      timeout: 1s
      retries: 5
    restart: always
    network_mode: host

  waves-node:
    container_name: waves-node
    image: wavesplatform/wavesnode:L2-20240507-819059ce4c
    environment:
      - JAVA_OPTS=-Dwaves.config.directory=/etc/waves -Dlogback.file.level=TRACE
    volumes:
      - ./waves:/var/lib/waves
      - ./log/waves:/var/log/waves
      - ./waves.conf:/etc/waves/waves.conf:ro
    depends_on:
      besu:
        condition: service_healthy
    restart: always
    network_mode: host
